language: csharp
mono: none
dotnet: 3.1.411
before_install:
 - chmod +x ./IllusionConnect.Data.Validator/IllusionConnect.Data.Validator.exe
script:
 - ./IllusionConnect.Data.Validator/IllusionConnect.Data.Validator.exe
